npm ci
NODE_ENV=production npm run build   # creates ./out
git checkout --orphan gh-pages
git --work-tree out add --all
git --work-tree out commit -m "Publish"
git push -f origin HEAD:gh-pages
git checkout -f main
git branch -D gh-pages
